# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
#services:
#  - name: redis:latest
#    alias: redis-adduser

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

variables:
  CASSANDRA_CONTACT_POINTS: "127.0.0.1"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

services:
  - redis:latest

stages:
- install_libs
- lint
- tests
- release

install_libs:
  stage: install_libs
  script:
    - npm install

lint:
  stage: lint
  script:
    - node_modules/eslint/bin/eslint.js libs/* index.js 

tests:
  stage: tests
  script:
    - npm test

release:
  image: node:13
  stage: release
  only:
    refs:
    - master
    - alpha
    # This matches maintenance branches
    - /^(([0-9]+)\.)?([0-9]+)\.x/
    # This matches pre-releases
    - /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/ 
  script:
    - npm install @semantic-release/gitlab
    - npx semantic-release
